version: '3'

services:
  frontend:
    container_name: frontend
    # TODO configure wordpress
    build: frontend/
    depends_on:
      - backend
    ports:
      - "8080:8080"
    environment:
        BACKEND_DNS: backend
        BACKEND_PORT: 9000

  backend:
    container_name: backend
    # TODO configure mysql
    build: backend/
    depends_on:
      - redis
    ports:
        - "9000:9000"
    environment:
        REDIS_DNS: redis

  redis:
    image: redis:alpine
