apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: production-backend
  name: production-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: production-backend
  strategy: {}
  template:
    metadata:
      labels:
        service: production-backend
    spec:
      containers:
      - env:
        - name: REDIS_DNS
          value: production-redis
        image: ttengs/fortune_cookie_backend:latest
        imagePullPolicy: ""
        name: production-backend
        ports:
        - containerPort: 9000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
