apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: dev-backend
  name: dev-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: dev-backend
  strategy: {}
  template:
    metadata:
      labels:
        service: dev-backend
    spec:
      containers:
      - env:
        - name: REDIS_DNS
          value: redis
        image: ttengs/fortune_cookie_backend:latest
        imagePullPolicy: ""
        name: dev-backend
        ports:
        - containerPort: 9000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
