apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: staging-backend
  name: staging-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: staging-backend
  strategy: {}
  template:
    metadata:
      labels:
        service: staging-backend
    spec:
      containers:
      - env:
        - name: REDIS_DNS
          value: staging-redis
        image: ttengs/fortune_cookie_backend:test
        imagePullPolicy: ""
        name: staging-backend
        ports:
        - containerPort: 9000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
