apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: dev-frontend
  name: dev-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: dev-frontend
  strategy: {}
  template:
    metadata:
      labels:
        service: dev-frontend
    spec:
      containers:
      - env:
        - name: BACKEND_DNS
          value: dev-backend
        - name: BACKEND_PORT
          value: "9000"
        image: ttengs/fortune_cookie_frontend:GA-83d5b5b7da64f7502b0b79507eefa852a98b95cc
        imagePullPolicy: ""
        name: dev-frontend
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
