apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: production-frontend
  name: production-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: production-frontend
  strategy: {}
  template:
    metadata:
      labels:
        service: production-frontend
    spec:
      containers:
      - env:
        - name: BACKEND_DNS
          value: production-backend
        - name: BACKEND_PORT
          value: "9000"
        image: ttengs/fortune_cookie_frontend:latest
        imagePullPolicy: ""
        name: production-frontend
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
