apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: production-redis
  name: production-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      service: production-redis
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: production-redis
    spec:
      containers:
      - image: redis:alpine
        imagePullPolicy: ""
        name: production-redis
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
