apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: {{NAME}}
  name: {{NAME}}
spec:
  replicas: 1
  selector:
    matchLabels:
      service: {{NAME}}
  strategy: {}
  template:
    metadata:
      labels:
        service: {{NAME}}
    spec:
      containers:
      - image: redis:alpine
        imagePullPolicy: ""
        name: dev-redis
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
