apiVersion: v1
kind: Service
metadata:
  labels:
    service: dev-backend
  name: dev-backend
spec:
  ports:
  - name: "9000"
    port: 9000
    targetPort: 9000
  selector:
    service: dev-backend
status:
  loadBalancer: {}
