apiVersion: v1
kind: Service
metadata:
  labels:
    service: staging-frontend
  name: staging-frontend
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    nodePort: 31376
  selector:
    service: staging-frontend
