apiVersion: v1
kind: Service
metadata:
  labels:
    service: production-frontend
  name: production-frontend
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    nodePort: 31255
  selector:
    service: production-frontend
