apiVersion: v1
kind: Service
metadata:
  labels:
    service: dev-frontend
  name: dev-frontend
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    nodePort: 32746
  selector:
    service: dev-frontend
