apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: staging-redis
  name: staging-redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    service: staging-redis
status:
  loadBalancer: {}
