on: 
  pull_request:
    branches:
      - main
name: Deployment
jobs:
  deploy:
    name: deploy to cluster
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - run: kubectl delete svc --all
    - run: kubectl delete deployments --all
    - run: kubectl apply -f ./kubernetes