on: 
  push:
    branches:
      - 02-co
  pull_request:
    branches:
      - main
name: deploy
jobs:
  deploy:
    name: deploy to cluster
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - run: kubectl apply -f ./kubernetes/redis-deployment.yaml
    - run: kubectl apply -f ./kubernetes/redis-service.yaml
    - run: kubectl apply -f ./kubernetes/backend-deployment.yaml
    - run: kubectl apply -f ./kubernetes/backend-service.yaml
    - run: kubectl apply -f ./kubernetes/frontend-deployment.yaml
    - run: kubectl apply -f ./kubernetes/frontend-service.yaml