on: 
  push:
    branches:
      - 02-co
  pull_request:
    branches:
      - main
name: deploy
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: deploy to cluster
      run: kubectl apply -f ./kubernetes