on: 
  push:
    branches:
      - 02-co
  pull_request:
    branches:
      - main
name: deploy
jobs:
  deploy:
    name: deploy to cluster
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - run: kubectl apply -f ./kubernetes
    #theis lugter