name: Fortune cookie CI
on: 
  push:
  pull_request:
    branches:
    - master
jobs:
  Clone-down:
    runs-on: self-hosted
    steps:
    - name: checkout
      uses: actions/checkout@v2
  Build:
    runs-on: self-hosted
    needs: Clone-down
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
    - name: Build backend
      run: cd backend && go build .
    - name: Build frontend
      run: cd frontend && go build .
  Test:
    runs-on: self-hosted
    needs: Clone-down
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
    - name: Test
      run: cd frontend && go test .