name: Fortune cookie CI
on: 
  push:
  pull_request:
    branches:
    - master
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Upload Repo
      uses: actions/upload-artifact@v2
      with:
        name: code
        path: .
  Build:
    runs-on: ubuntu-latest
    needs: Clone-down
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
    - name: Build backend
      run: cd backend && go build .
    - name: Build frontend
      run: cd frontend && go build .
  Test:
    runs-on: ubuntu-latest
    needs: [Clone-down, Build]
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
    - name: Test
      run: cd frontend && go test .
