name: Fortune cookie CI
on: 
  push:
  pull_request:
    branches:
    - master
jobs:
  Clone-down:
    runs-on: self-hosted
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Upload Repo
      uses: actions/upload-artifact@v2
      with:
        name: code
        path: /test
  Build:
    runs-on: self-hosted
    needs: Clone-down
    steps:
    - run: whoami
    - run: ls
    - run: pwd
    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
        name: code
        path: /test
    - name: Install Go
      uses: actions/setup-go@v2
    - name: Build backend
      run: cd backend && go build .
    - name: Build frontend
      run: cd frontend && go build .
  Test:
    runs-on: self-hosted
    needs: Clone-down
    steps:
    - run: whoami
    - run: ls
    - run: pwd
    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
        name: code
        path: .
    - name: Install Go
      uses: actions/setup-go@v2
    - name: Test
      run: cd frontend && go test .